"mv t0, %[b]\n\t"
"mv t1, %[temp]\n\t"
"li t2, 0\n\t"
"1:\n\t"
"andi t3, t0, 1\n\t"
"sll t3, t3, t1\n\t"
"or t2, t2, t3\n\t"
"srl t0, t0, 1\n\t"
"addi t1, t1, -1\n\t"
"bnez t0, 1b\n\t"
"mv %[b], t2\n\t"
"addi %[lw_cnt], %[lw_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 7\n\t"
