"mv t0, %[N]\n\t"
"li t1, 0\n\t"
"1:\n\t"
"srli t0, t0, 1\n\t"                    
"addi t1, t1, 1\n\t"                    
"addi %[add_cnt], %[add_cnt], 1\n\t"   
"addi %[others_cnt], %[others_cnt], 1\n\t" 
"j 1b\n\t"
"2:\n\t"
"mv %[log], t1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t" 