"li t1, 0\n\t"
"fcvt.s.w f0, zero\n\t"
"li t2, 0\n\t"
"1:\n\t"
"fcvt.s.w f1, t2\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"fadd.s f2, f1, f1\n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"fadd.s f2, f2, f1\n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"fdiv.s f3, f1, f2\n\t"
"addi %[fdiv_cnt], %[fdiv_cnt], 1\n\t"
"andi t3, t2, 1\n\t"
"beqz t3, 2f\n\t"
"fneg.s f3, f3\n\t"
"2:\n\t"
"fadd.s f0, f0, f3\n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"addi t2, t2, 1\n\t"
"blt t2, %[N], 1b\n\t"
